name: Deploy Laravel API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Current directory:"
            pwd

            echo "Current user:"
            whoami

            echo "Directory contents:"
            ls -la

            echo "Searching for Laravel artisan files:"
            find $HOME -name artisan 2>/dev/null | head -20
